# RAG System Configuration
# Copy this file to config.yaml and customize for your needs

# Data source configuration
data:
  # Path to your documentation directory (relative to project root)
  source_dir: "./docs"
  # Supported file extensions
  file_extensions: [".md", ".txt"]
  # Company/project name (used for display purposes)
  company_name: "Documentation"
  # Dataset description
  dataset_description: "Technical documentation and API references"

# Ollama configuration
ollama:
  # Base URL for Ollama API
  base_url: "http://localhost:11434"
  # Model for generating embeddings
  embedding_model: "nomic-embed-text"
  # Model for chat/question answering
  chat_model: "llama2"
  # Request timeout in seconds
  timeout: 30

# Text processing configuration
processing:
  # Maximum chunk size in characters
  chunk_size: 1000
  # Overlap between chunks in characters
  chunk_overlap: 200
  # Minimum chunk size to keep
  min_chunk_size: 100
  # Maximum number of chunks to retrieve for context
  max_retrieved_chunks: 5

# Vector database configuration
vector_db:
  # Type of vector database (currently supports: chromadb, faiss)
  type: "chromadb"
  # Path to store vector database
  path: "./vector_db"
  # Collection name
  collection_name: "documents"
  # Distance metric for similarity search
  distance_metric: "cosine"

# CLI configuration
cli:
  # Maximum number of previous questions to show
  history_size: 10
  # Whether to show sources with answers
  show_sources: true
  # Number of sources to show
  max_sources: 3

# Logging configuration
logging:
  level: "INFO"
  file: "rag_system.log"